// app.vue
<template>
	<nav id="top">
		<h1><NuxtLink to="/">Ludoviko</NuxtLink></h1>
	</nav>
	<NuxtPage />
	<footer>
		© 2020-2022 Ludoviko - The MIT License |
		<NuxtLink to="/privacy">Privacy</NuxtLink>
	</footer>
</template>

<script setup>
useHead({
	titleTemplate: (title) => {
		return title ? `${title} | Ludoviko` : "Ludoviko";
	},
	link: [{ rel: "icon", src: "/RingRingTechSupport.ico" }],
	meta: [
		{ property: "og:title", content: "Ludoviko" },
		{
			name: "description",
			content: "Ludoviko's little place on the internet",
		},
		{
			property: "og:description",
			content: "Ludoviko's little place on the internet",
		},
		{
			property: "og:type",
			content: "website",
		},
		{
			property: "og:image",
			content: "https://ludoviko.ch/RingRingTechSupport.png",
		},
		{
			name: "keywords",
			content:
				"Ludoviko, Programming, Minecraft, Game Development, Java, Blog, Kotlin",
		},
		{
			property: "twitter:card",
			content: "summary",
		},
		{
			property: "twitter:site",
			content: "@Ludoviko_",
		},
		{
			property: "twitter:creator",
			content: "@Ludoviko_",
		},
	],
});
</script>

<style lang="scss" scoped>
a {
	color: azure;
}
</style>

// pages/_app.tsx
import '../styles/globals.scss'
import 'bootstrap/dist/css/bootstrap.css'
import '@dracula/dracula-ui/styles/dracula-ui.css'
import { AppProps } from 'next/app'
import Navigation from '../components/nav'
import Footer from '../components/footer'
import Head from 'next/head'
import PlausibleProvider from 'next-plausible'

function App({ Component, pageProps }: AppProps) {
  return (
		<>
			<PlausibleProvider trackOutboundLinks={true} domain="ludoviko.xyz">
				<Head>
					<link rel="icon" href="/RingRingTechSupport.ico" />
					<meta property="og:title" content="Ludoviko" key="title" />
					<meta
						name="description"
						content="Ludoviko's little place on the internet"
						key="desc"
					/>
					<meta
						property="og:description"
						content="Ludoviko's little place on the internet"
						key="og:desc"
					/>
					<meta property="og:type" content="website" key="og:type" />
					<meta
						property="og:image"
						content="https://ludoviko.ch/RingRingTechSupport.png"
						key="og:img"
					/>
					<meta
						name="keywords"
						content="Ludoviko, Programming, Minecraft, Game Development, Java, Blog, Kotlin"
						key="keyw"
					/>
					<meta name="twitter:card" content="summary" />
					<meta name="twitter:site" content="@Ludoviko_" />
					<meta name="twitter:creator" content="@Ludoviko_" />
					<script type="text/javascript" src="/iubenda.js" />
					<script
						type="text/javascript"
						src="//cdn.iubenda.com/cs/tcf/stub-v2.js"></script>
					<script
						type="text/javascript"
						src="//cdn.iubenda.com/cs/iubenda_cs.js"
						async></script>
					<script
						dangerouslySetInnerHTML={{
							__html: `
            window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }
          `,
						}}></script>
				</Head>
				<Navigation />
				<Component {...pageProps} />
				<Footer />
			</PlausibleProvider>
		</>
  );
}

export default App
